### ISSUE TITLE
let operation for untyped lamba

### ISSUE THREAD

**Issue by andreykl** [sgillespie/lambda-calculus#2]
Good job, thank you!

one notice: when I try to use it to check something like tail for church list, I have to type rather many symbols. and it is a bit annoying to fix mistypes and check parts of expressions.

if it would be possible to have something like 
```
let NIL = \c n. n
let CONS = \e l c n . e c (l c n)
```
this would be very helpful.
what do you think?

**Comment by sgillespie** [comment]
I think it's reasonable request

**Comment by andreykl** [comment]
I'm just interested to see/check whether things I wrote do really work as expected, while studying lambda calculus.

**Comment by sgillespie** [comment]
This is available in v3.0.0.0
