### ISSUE TITLE
typo hyperlink on doc/lambda-calculus.md

### ISSUE THREAD

**Issue by terrychan999** [sgillespie/lambda-calculus#5]
The hyperlink of the first reference is invalid:
`1. [Lambda Calculus](https://en.wikipedia.org/wiki/Lambd.a_calculus). Wikipedia: The Free Encyclopedia`
it should be
`1. [Lambda Calculus](https://en.wikipedia.org/wiki/Lambda_calculus). Wikipedia: The Free Encyclopedia`

**Comment by sgillespie** [comment]
Good eye, I've corrected the reference. Thanks!
